### ISSUE TITLE
The UI could use some improvement.

### ISSUE THREAD

**Issue by tarothanawat** [NewOsakA/ku-polls#29]
The overall UI looks ok, but I think the texts are too small. There are still so many space left on the screen so maybe you could make the texts and components bigger.
![image](https://github.com/user-attachments/assets/1491c6a0-6e6c-4ed2-8691-acd3b24eaae1)

And you could use some CSS styling (something like buttons ) on "Back to polls" and "Results" link to make it be more visible. I can barely see it.

**Comment by NewOsakA** [comment]
"Back to Polls" and "Results" are now buttons. The text size will stay consistent, adjusting according to the user's screen resolution, which may cause it to appear smaller or larger.
