### ISSUE TITLE
Installation guide looks good but,

### ISSUE THREAD

**Issue by tarothanawat** [NewOsakA/ku-polls#30]
The installation guide you have looks good! But in 
![image](https://github.com/user-attachments/assets/a084003e-994b-4278-8668-5226debd22a1)

![image](https://github.com/user-attachments/assets/49940a9d-628e-4040-b287-b45a28f27034)

Why not put the commands that you give in sample.env into the installation guide. I think it will a much easier for users to follow along, but this is just me being picky though you don't really have to do it.

**Comment by NewOsakA** [comment]
Fixed
